### ISSUE TITLE
tgif.py defaults to using cuda even when GPU is not present

### ISSUE THREAD

**Issue by Jerdak** [rowanz/pytorch-seq2seq#1]
I'm not sure if this is intended behavior but at [dad9e6d/dataloaders/tgif.py#L157](https://github.com/rowanz/pytorch-seq2seq/blob/dad9e6dbcdd77906b878a9acebe3edfdfa31f8da/dataloaders/tgif.py#L157) there is a call to [Pytorch/Text](https://github.com/pytorch/text) that is forcing the **pytorch-seq2seq** to default to CUDA even in the absence of a GPU.  Specifically this line:

`seq, lens = self.dataset.caps_field.numericalize(batch, train=self.dataset.is_train)`

The unused `device` parameter is defaulting to `None` which is telling `numericalize` to use the currently active GPU. 

>  device: Device to create the Variable's Tensor on. Use -1 for CPU and None for the currently active GPU device. Default: None.

 In my case I don't have an active GPU (virtual machine) and I guess PyTorch/Text doesn't have an automatic fallback to CPU.

**Comment by rowanz** [comment]
thanks for the note! Sorry for taking so long to fix this - this should be fixed by 0baaf07 :) As a sidenote, I'm not sure how feasible video captioning will be on CPU.
